# Force OpenSL ES output since it works across all Android hardware architectures
ao=opensles

# Completely disable the video decoder to save memory and avoid window errors
vid=no

# Force the output format to standard 16-bit PCM if high-resolution audio causes crackling
audio-format=s16

# Keep terminal playback alive even when switching app focus
keep-open=yes
